# Generated by Django 4.0.6 on 2023-11-09 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('tel_fixe', models.CharField(max_length=30)),
                ('tel_mobile_1', models.CharField(max_length=30)),
                ('tel_mobile_2', models.CharField(max_length=30)),
                ('chef_lieu', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ville', models.CharField(max_length=30)),
                ('quartier', models.CharField(default='', max_length=30)),
                ('category', models.CharField(max_length=100)),
                ('speciality', models.CharField(default='', max_length=100)),
                ('nom', models.CharField(default='', max_length=50)),
                ('horaire', models.CharField(default='08h-20h', max_length=50)),
                ('property', models.CharField(default='PRIVEE', max_length=30)),
                ('nom_complet', models.CharField(default='', max_length=30)),
                ('telephone', models.CharField(default='', max_length=30)),
                ('nbr_porte', models.IntegerField(default=1)),
                ('coords', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diaffrin_api.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_device', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=-1)),
                ('month', models.CharField(max_length=20)),
                ('montant', models.IntegerField(default=0)),
                ('date_reference', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('coords', models.CharField(max_length=100)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diaffrin_api.entity')),
            ],
        ),
    ]
