# Generated by Django 4.2.5 on 2023-09-25 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('tel_fixe', models.CharField(max_length=30)),
                ('tel_mobile_1', models.CharField(max_length=30)),
                ('tel_mobile_2', models.CharField(max_length=30)),
                ('chef_lieu', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('ville', models.CharField(max_length=30)),
                ('quartier', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=30)),
                ('secteur', models.CharField(max_length=30)),
                ('speciality', models.CharField(max_length=30)),
                ('horaire', models.CharField(max_length=30)),
                ('contact_name', models.CharField(max_length=30)),
                ('contact_prenom', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=30)),
                ('n_porte', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('proprerty', models.CharField(max_length=30)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diaffrin_api.commune')),
            ],
        ),
    ]
