# Generated by Django 4.0.6 on 2023-11-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaffrin_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='nom_complet',
            field=models.CharField(blank=True, default='No', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='quartier',
            field=models.CharField(blank=True, default='No', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='speciality',
            field=models.CharField(blank=True, default='No', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='telephone',
            field=models.CharField(blank=True, default='-1', max_length=30, null=True),
        ),
    ]
