# Generated by Django 4.0.6 on 2023-11-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaffrin_api', '0002_alter_entity_nom_alter_entity_nom_complet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='nom_complet',
            field=models.CharField(blank=True, default='No', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='quartier',
            field=models.CharField(blank=True, default='No', max_length=50, null=True),
        ),
    ]
