PROPERTY_LIST = [
    "PRIVEE",
    "ESPACE PUBLIC",
    "MARCHE",
]

ACTIVITY_LIST = [
    "Boutique divers",
    "Boutique spécialisée",
    "Autres commerces",
    "Autres services",
    "Alimentation",
    "Boucherie",
    "Boulangerie",
    "Coiffure",
    "Couture",
    "Electronique",
    "Formation",
    "Garage Moto",
    "Garage Auto",
    "Garage Pneu",
    "Grabale",
    "Poissonnerie",
    "Volaille",
    "Industrie bois",
    "Industrie metallique",
    "Lavage",
    "Loisir",
    "Magasin de depots",
    "Magasin fermée",
    "Moulin",
    "Or",
    "Quincaillerie",
    "Rebobinage",
    "Restauration",
    "Santé",
    "Service reparation",
    "Table Fruits",
    "Table condiments",
    "Transfert financier",
    "Media",
    "Katakatani",
    "Moto Taxi",
    "Transport",
    "Textile",
    "Technologie",
    "Restaurant",
    "Boisson",
]

# choices.py (recommended)
LOCALITY_LIST = [
    "Kalana Centre",
    "Kalana Koko",
    "Kalana Kelibougou",
    "Kalana Camp coroni",
    "Kalana Camp",
    "Kalana Dabaranbougou",
    "Kalana",
]

PROPERTY_LIST = [
    "PRIVEE",
    "ESPACE PUBLIC",
    "MARCHE",
]

ACTIVITY_LIST = [
    "Boutique divers",
    "Boutique spécialisée",
    "Autres commerces",
    "Autres services",
    "Alimentation",
    "Boucherie",
    "Boulangerie",
    "Coiffure",
    "Couture",
    "Electronique",
    "Formation",
    "Garage Moto",
    "Garage Auto",
    "Garage Pneu",
    "Grabale",
    "Poissonnerie",
    "Volaille",
    "Industrie bois",
    "Industrie metallique",
    "Lavage",
    "Loisir",
    "Magasin de depots",
    "Magasin fermée",
    "Moulin",
    "Or",
    "Quincaillerie",
    "Rebobinage",
    "Restauration",
    "Santé",
    "Service reparation",
    "Table Fruits",
    "Table condiments",
    "Transfert financier",
    "Media",
    "Katakatani",
    "Moto Taxi",
    "Transport",
    "Textile",
    "Technologie",
    "Restaurant",
    "Boisson",
]

STATUS_LIST = [
    "OUVERT",
    "ABSENT",
    "FERME",
]

LOCALITY_LISTS = [
    'Kalana',
    "Kalana Centre",
    "Kalana Koko",
    "Kalana Kelibougou",
    "Kalana Camp coroni",
    "Kalana Camp",
    "Kalana Dabaranbougou",
]

PLACES = [
    "Kalana",
    "Niessoumala",
    "Traorela",
    "Diabala",
    "Balantoumou",
    "Faboula",
    "Kalako",
    "Ladjikouroula",
    "Solomanina",
    "Sadiouroula",
    "Daolila",
    "Dadjougoubala",
    "Bada",
    "Bandiala",
    "Bèrèbogola",
    "Dabaran",
    "Dalaguè",
    "Dangouè",
    "Diansirala",
    "Hadjila",
    "Hadjilaminina",
    "Konfra",
    "Kossiala",
    "Koumbala",
    "Lèba",
    "Mandebala",
    "Nènèdiana",
    "Nounfra",
    "Salala",
    "Samerila",
    "SôkôrôKô",
]
